apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: geotrack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-binding
  namespace: geotrack
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
roleRef:
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-geotrack-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: geotrack
roleRef:
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
  apiGroup: rbac.authorization.k8s.io
